language: ruby
cache: bundler
sudo: false
notifications:
  email: false

rvm:
  - 2.2

env:
  global:
    - JRUBY_OPTS="-J-Xms512m -J-Xmx1024m"
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: bundle exec rake ci
